.TH "C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/NimbleGraphics Directory Reference" 3 "Mon Aug 17 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/NimbleGraphics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDirectX11\fP"
.br
.ti -1c
.RI "directory \fBDirectX12\fP"
.br
.ti -1c
.RI "directory \fBOpenGL\fP"
.br
.ti -1c
.RI "directory \fBVulkan\fP"
.br
.in -1c
