.TH "src Directory Reference" 3 "Wed Aug 19 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBNimbleEngine\fP"
.br
.ti -1c
.RI "directory \fBNimbleGraphics\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNimbleEngine\&.c\fP"
.br
.ti -1c
.RI "file \fBNimbleLicense\&.c\fP"
.br
.RI "Defines the value of \fBLICENSE_md\fP, which gets compiled into the binaries\&. "
.in -1c
