.TH "C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/NimbleGraphics/DirectX12 Directory Reference" 3 "Sun Aug 16 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/NimbleGraphics/DirectX12 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHardware\&.h\fP"
.br
.ti -1c
.RI "file \fBOverlay\&.h\fP"
.br
.ti -1c
.RI "file \fBRender\&.h\fP"
.br
.ti -1c
.RI "file \fBShaders\&.h\fP"
.br
.ti -1c
.RI "file \fBWindow\&.h\fP"
.br
.ti -1c
.RI "file \fBWindowEvents\&.h\fP"
.br
.in -1c
