.TH "C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/src Directory Reference" 3 "Fri Aug 14 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBNimbleEngine\fP"
.br
.ti -1c
.RI "directory \fBNimbleGraphics\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNimble\&.h\fP"
.br
.RI "Defines the macros that are used by other files\&. "
.ti -1c
.RI "file \fBNimbleDirectX11\&.h\fP"
.br
.RI "Defines all the graphics functions for DirectX11\&. "
.ti -1c
.RI "file \fBNimbleDirectX12\&.h\fP"
.br
.RI "Defines all the graphics functions for DirectX12\&. "
.ti -1c
.RI "file \fBNimbleEngine\&.c\fP"
.br
.ti -1c
.RI "file \fBNimbleEngine\&.h\fP"
.br
.RI "Includes all the necessary game engine header files\&. "
.ti -1c
.RI "file \fBNimbleOpenGL\&.h\fP"
.br
.RI "Defines all the graphics functions for OpenGL\&. "
.ti -1c
.RI "file \fBNimbleVulkan\&.h\fP"
.br
.RI "Defines all the graphics functions for Vulkan\&. "
.in -1c
