.TH "C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/Nimble.h" 3 "Mon Aug 17 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/include/Nimble/Nimble.h \- Defines the macros that are used by other files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'NimbleLicense\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNIMBLE_H\fP"
.br
.RI "Header definition\&. "
.ti -1c
.RI "#define \fBNIMBLE_EXPORT\fP"
.br
.RI "Export alias\&. "
.ti -1c
.RI "#define \fBNIMBLE_LOCAL\fP"
.br
.RI "Local alias\&. "
.ti -1c
.RI "#define \fBNIMBLE_INLINE\fP   static inline __attribute__((always_inline))"
.br
.RI "Inline alias\&. "
.ti -1c
.RI "#define \fBNIMBLE_EXTERN\fP   extern"
.br
.RI "Extern alias\&. "
.ti -1c
.RI "#define \fBNULL\fP   ((void *) 0)"
.br
.RI "Null pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the macros that are used by other files\&. 


.PP
\fBAuthor\fP
.RS 4
Avery Aaron 
.RE
.PP
\fBCopyright\fP
.RS 4
The MIT License (MIT) Copyright (C) 2020 Avery Aaron business.a3ology@gmail.com
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&. 
.RE
.PP
.PP
\fBDate\fP
.RS 4
2020-08-14
.RE
.PP
This header defines the macros that are used by other files\&. 
.PP
Definition in file \fBNimble\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define NIMBLE_EXPORT"

.PP
Export alias\&. 
.PP
Definition at line 109 of file Nimble\&.h\&.
.SS "#define NIMBLE_EXTERN   extern"

.PP
Extern alias\&. 
.PP
Definition at line 115 of file Nimble\&.h\&.
.SS "#define NIMBLE_H"

.PP
Header definition\&. 
.PP
Definition at line 81 of file Nimble\&.h\&.
.SS "#define NIMBLE_INLINE   static inline __attribute__((always_inline))"

.PP
Inline alias\&. 
.PP
Definition at line 112 of file Nimble\&.h\&.
.SS "#define NIMBLE_LOCAL"

.PP
Local alias\&. 
.PP
Definition at line 110 of file Nimble\&.h\&.
.SS "#define NULL   ((void *) 0)"

.PP
Null pointer\&. 
.PP
Definition at line 118 of file Nimble\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Nimble Game Engine Library from the source code\&.
