.TH "C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/src/NimbleGraphics/Vulkan/Render.h" 3 "Fri Aug 14 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Avery/Desktop/Nimble Game Engine/Nimble Game Engine Library/src/NimbleGraphics/Vulkan/Render.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./\&.\&./\&.\&./License/NimbleLicense\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./NimbleVulkan\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNIMBLE_GRAPHICS_RENDER_H\fP"
.br
.RI "Header definition\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NIMBLE_GRAPHICS_RENDER_H"

.PP
Header definition\&. 
.PP
Definition at line 16 of file Render\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Nimble Game Engine Library from the source code\&.
