.TH "todo" 3 "Mon Aug 17 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBpage \fBNimble Game Engine Library\fP \fP" 1c
Explain how to link the library or use the app to write code 
.PP
Explain how to get started, setting up a window and doing basic 2D/3D stuff
.PP

