.TH "todo" 3 "Tue Aug 18 2020" "Version 0.1.0" "Nimble Game Engine Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBnErrorThrow\fP (const int32_t error, const char *info, int32_t infoLen)\fP" 1c
Crash\&. 
.PP
Crash\&. 
.PP
Crash\&.  
.IP "\fBGlobal \fBnErrorToString\fP (char *dst, int32_t *size, const int32_t error, const char *info, int32_t infoLen)\fP" 1c
Crash\&.  
.IP "\fBGlobal \fBnErrorGetStacktrace\fP (char *dst, int32_t *size, int32_t *levels)\fP" 1c
Get stack trace\&.  
.IP "\fBpage \fBNimble Game Engine Library\fP \fP" 1c
Explain how to link the library or use the app to write code 
.PP
Explain how to get started, setting up a window and doing basic 2D/3D stuff
.PP

